language: node_js
node_js:
  - '20'
install:
  - npm install
script:
  - npm run predeploy
  - npm run deploy:ci
branches:
  only:
    - develop
notifications:
  email:
    recipients:
      - thisisbinbin@gmail.com
    on_success: always
